spring.application.name=kadai

# ----- H2 Database接続 -----
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa	
spring.datasource.password=
spring.sql.init.encoding=UTF-8 	
spring.datasource.initialize=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.schema-locations=classpath:sql/schema.sql 	
spring.sql.init.shain-locations=classpath:sql/shain.sql
spring.datasource.generate-unique-name=false 	


# ----- MariaDB接続 -----
#spring.datasource.url=jdbc:mariadb://10.0.3.117:3307/sampledb
#spring.datasource.username=kadai26
#spring.datasource.password=kadai26
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=1
#spring.jpa.open-in-view=false
##--自分で書いた↓
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


#logging.level.org.springframework.boot.autoconfigure=DEBUG

