
CREATE TABLE SHAIN_TBL(
    SHAINCD VARCHAR(20),
    SHAINNM VARCHAR(20),
    RANK1 VARCHAR(20),
    RANK2 VARCHAR(20),
    RANK3 VARCHAR(20),
    JOB VARCHAR(20),
    INTRO VARCHAR(20),
    PRIMARY KEY(SHAINCD)
);


CREATE TABLE LOGIN_TBL(
    USERID VARCHAR(20),
    PASSWORD VARCHAR(20),
    PRIMARY KEY(USERID)
);
