DROP TABLE IF EXISTS TEAM20_SHAIN_TBL;

CREATE TABLE TEAM20_SHAIN_TBL(
    SHAINCD VARCHAR2(20),
    SHAINNM VARCHAR2(20),
    RANK1 VARCHAR2(20),
    RANK2 VARCHAR2(20),
    RANK3 VARCHAR2(20),
    JOB VARCHAR2(20),
    INTRO VARCHAR2(200),

    PRIMARY KEY(SHAINCD)
);

DROP TABLE IF EXISTS TEAM20_LOGIN_TBL;
CREATE TABLE TEAM20_LOGIN_TBL(
    USERID VARCHAR(20),
    PASSWORD VARCHAR(20),
    PRIMARY KEY(USERID)
);

DROP TABLE IF EXISTS TEAM20_HOBBY_TBL;

CREATE TABLE TEAM20_HOBBY_TBL(
    HOBBYCODE VARCHAR2(20), 
    JANRU      VARCHAR2(50),
    HOBBY      VARCHAR2(50),
    PRIMARY KEY(HOBBYCODE)
);
